- id: '1588201352119'
  alias: New Automation
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_pool_gate
    for: 0:05:00
    from: closed
    platform: state
    to: open
  condition: []
  action:
  - data:
      type: tts
    service: notify.alexa_media_stereo_sub_pair

- id: '1588201418994'
  alias: test
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_pool_gate
    for: '5'
    from: closed
    platform: state
    to: open
  condition: []
  action:
  - data: {}
    service: notify.alexa_media_stereo_sub_pair

- alias: "Mail Notif - Mail Delieveries"
  initial_state: 'on'
  trigger:
  #Trigger if mail or packages get updated
    - platform: state
      entity_id: sensor.mail_usps_mail
    - platform: state
      entity_id: sensor.mail_usps_delivering
  #send only if mail or packages are more than 0
  condition:
    - condition: or
      conditions:
        - condition: template
          value_template: "{{ states('sensor.mail_usps_mail') | int > 0 }}"
        - condition: template
          value_template: "{{ states('sensor.mail_usps_delivering') | int > 0 }}"
  action:
    - service: notify.notify
      data_template:
        title: "*Today's Mail and Packages*"
        message: "{{ states('sensor.mail_deliveries_message')}}"
    - service: notify.notify
      data:
        message: "Here is the mail"
        data:
          document:
            file: "/local/images/mail_and_packages/mail_today.gif"

