# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  unit_system: imperial
  time_zone: America/Phoenix
  name: Kelsall Home Assistant
  whitelist_external_dirs:
    - '/config/'
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - 192.168.86.0/24
      allow_bypass_login: true
    - type: homeassistant

default_config:

recorder:
  db_url: mysql://hass:BiCjsNZ6@core-mariadb/homeassistant?charset=utf8

lovelace:
  mode: yaml

hacs:
  token: !secret hacs_token

frontend:
   themes: !include_dir_merge_named themes

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: cheese-io.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Sensors
#sensor: !include sensors.yaml

wemo:
    discovery: true 
    
cover:
  - platform: myq
    username: !secret myq_user
    password: !secret myq_pass
    type: liftmaster
    
media_player:
  - platform: androidtv
    name: Master Fire TV
    host: 192.168.0.59

amcrest:
  - host: 192.168.0.46
    username: admin
    password: cpQhFJ*39
    name: "Courtyard Camera"
    stream_source: rtsp
    binary_sensors:
      - motion_detected
      - online

ecovacs:
  username: !secret ecovac_user
  password: !secret ecovac_pass
  country: us
  continent: na

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

google:
  client_id: !secret google_client
  client_secret: !secret google_secret

simplisafe:
  accounts:
    - username: !secret simplisafe_user
      password: !secret simplisafe_pass

#influxdb:
  #host: 192.168.0.174
  #port: 8086
  #database: sensors
  #username: sensor_store
  #password: BiCjsNZ6
  #include:
    #entities:
      #- sensor.edgesurvey_stream

#shell_command:
#  tv_pcap: timeout 10s netcat  192.168.0.19 7070 > /usr/shar/hassio/homeassistant/www/pcaps/KitchenNightmare.`echo $(date +%s)`.pcap
