resources:
  - url: /local/custom-ui/weather-card/dist/weather-card.js
    type: js

title: 'Kelsall Home'
views:

# MAIN VIEW
  - path: default_view
    title: ''
    icon: 'mdi:home'
    badges:
      - entity: binary_sensor.updater
      - entity: person.james
    cards:
      - entity: weather.dark_sky
        type: custom:weather-card
        current: true
        details: false
        forecast: true
      - entities:
          - entity: cover.garage_door
          - entity: switch.courtyard
          - entity: switch.garage
          - entity: switch.ice_machine
        type: glance
      - entity: alarm_control_panel.1821_e_hope_st_alarm_control_panel
        name: Alarm Control
        type: alarm-panel

# CLIMATE CONTROL
  - panel: false
    title: ''
    icon: 'mdi:thermometer-lines'
    badges: []
    cards:
      - entity: climate.kids_rooms
        type: thermostat
      - entity: weather.home
        theme: Backend-selected
        type: weather-forecast
      - entity: climate.dining_room
        type: thermostat

# LIGHTS
  - icon: 'mdi:lightbulb'
    panel: false
    path: lights
    theme: default
    title: ''
    badges: []
    cards:
      - type: entity-button
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        entity: switch.garage
        name: Driveway Lights
        icon: 'mdi:lightbulb'
      - type: entity-button
        tap_action:
          action: toggle
        hold_action:
          action: none
        show_icon: true
        show_name: true
        entity: switch.courtyard
        name: Courtyard Lights
        theme: Backend-selected
        icon: 'mdi:lightbulb'

# MEDIA
  - path: media
    title: ''
    icon: 'mdi:movie-outline'
    badges: []
    cards: 
      - type: media-control
        entity: media_player.onkyo_tx_nr676_eee2a4


