custom_header:
  compact_mode: true
  hide_config: true
  exceptions:
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true

resources:
  - url: /hacsfiles/calendar-card/calendar-card.js
    type: module
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/surveillance-card/surveillance-card.js
    type: module
  - url: /hacsfiles/weather-card/weather-card.js
    type: js

title: 'Kelsall Home'
views:

# 1 MAIN VIEW
  - id: home
    path: home
    panel: false
    title: ''
    icon: 'mdi:home'
    badges:
      - entity: binary_sensor.updater
      - entity: person.james_kelsall
      - entity: person.jen
    cards:
 #     - type: 'custom:atomic-calendar'
 #       title: 'Home Calendar'
 #       showMonth: true
 #       maxDaysToShow: 7
 #       defaultMode: 1
 #       dayWrapperLineColor: orange
 #       entities:
 #         - entity: calendar.family_calendar
 #         - entity: calendar.macarthur_calendar
 #         - entity: calendar.mpsaz_calendar
      - type: 'custom:calendar-card'
        title: "My Calendar"
        progressBar: true
        entities:
         - entity: calendar.family_calendar
      - entity: weather.dark_sky
        type: custom:weather-card
        current: true
        details: false
        forecast: true
      - type: glance
        entities:
          - entity: cover.garage_door
          - entity: switch.courtyard_lights
          - entity: switch.driveway_lights
          - entity: switch.sideyard
          - entity: switch.projector
          - entity: switch.ice_machine
      - entity: alarm_control_panel.1821_e_hope_st_alarm_control_panel
        name: Alarm Control
        type: alarm-panel
      - type: entities
        entities:
          - switch.stereo_sub_pair_do_not_disturb_switch
          - switch.stereo_sub_pair_repeat_switch
          - switch.stereo_sub_pair_shuffle_switch
      - type: media-control
        entity: media_player.stereo_sub_pair

#      - type: entities
#        title: Lunch Menu
#        entities:
#          - entity: sensor.first_menu_item
#            name: ' '
#          - entity: sensor.second_menu_item
#            name: ' '

# 2 CLIMATE CONTROL
  - id: thermostat
    path: thermostat
    panel: false
    title: ''
    icon: 'mdi:thermometer-lines'
    cards:
      - entity: weather.dark_sky
        type: custom:weather-card
        current: true
        details: false
        forecast: true
      - entity: climate.kids_rooms
        type: thermostat
      - entity: climate.dining_room
        type: thermostat

# 3 LIGHTS
  - id: lights
    path: lights
    icon: 'mdi:lightbulb'
    panel: false
    title: ''
    badges: []
    cards:
      - type: entity-button
        tap_action:
          action: toggle
        hold_action:
          action: more-info
        show_icon: true
        show_name: true
        entity: switch.garage
        name: Driveway Lights
        icon: 'mdi:lightbulb'
      - type: entity-button
        tap_action:
          action: toggle
        hold_action:
          action: none
        show_icon: true
        show_name: true
        entity: switch.courtyard
        name: Courtyard Lights
        theme: Backend-selected
        icon: 'mdi:lightbulb'

# 4 MEDIA
  - id: media
    path: media
    title: ''
    icon: 'mdi:movie-outline'
    badges: []
    cards: 
      - type: media-control
        entity: media_player.onkyo_tx_nr676_eee2a4

# 5 SREAMING STATS
  - id: stream_stats
    path: stream_stats
    title: ''
    icon: 'mdi:youtube-tv'
    cards:
      - type: history-graph
        entities:
          - sensor.samsung_tv

# 6 SURVEILLANCE
  - id: cameras
    path: cameras
    title: Surveillance
    panel: true
    icon: mdi:cctv
    cards:
      - type: custom:surveillance-card
        thumb_interval: 15
        update_interval: 2
        cameras:
          - entity: camera.courtyard_camera
            motion_entity: binary_sensor.courtyard_camera_motion

